using System;
using UnityEngine;

namespace ASTRA.UAV.Interfaces
{
    /// <summary>
    /// AI Navigation goal structure.
    /// </summary>
    [Serializable]
    public struct AIGoal
    {
        /// <summary>Goal identifier or description.</summary>
        public string GoalId;

        /// <summary>Target position in local coordinate space.</summary>
        public Vector3 TargetPosition;

        /// <summary>Target velocity vector if dynamic intercept.</summary>
        public Vector3 TargetVelocity;

        /// <summary>Tolerance distance in meters for goal completion.</summary>
        public float TargetTolerance;

        /// <summary>Priority level of this goal (higher = preceding priority).</summary>
        public int Priority;
    }

    /// <summary>
    /// Control command output generated by an AI module.
    /// </summary>
    [Serializable]
    public struct AICommandOutput
    {
        /// <summary>Target velocity vector output by AI (m/s).</summary>
        public Vector3 DesiredVelocity;

        /// <summary>Target yaw angle or yaw rate output by AI.</summary>
        public float DesiredYawRate;

        /// <summary>Confidence metric of the AI action [0..1].</summary>
        public float Confidence;

        /// <summary>True if obstacle emergency evasion maneuver is active.</summary>
        public bool IsEvasionActive;
    }

    /// <summary>
    /// Contract for pluggable AI navigation, pathfinding, and autonomous decision modules.
    /// </summary>
    public interface IAIModule
    {
        /// <summary>
        /// Gets the human-readable identifier for this AI module.
        /// </summary>
        string ModuleName { get; }

        /// <summary>
        /// Gets a value indicating whether the AI module has been initialized.
        /// </summary>
        bool IsInitialized { get; }

        /// <summary>
        /// Gets or sets a value indicating whether the AI module actively evaluates inputs.
        /// </summary>
        bool IsActive { get; set; }

        /// <summary>
        /// Gets the target update interval in seconds for AI decision steps.
        /// </summary>
        float UpdateIntervalSeconds { get; }

        /// <summary>
        /// Fired when new control commands are produced by the AI module.
        /// </summary>
        event Action<AICommandOutput> OnAICommandGenerated;

        /// <summary>
        /// Fired when an internal AI evaluation error or exception occurs.
        /// </summary>
        event Action<string> OnAIError;

        /// <summary>
        /// Initializes internal AI neural networks, heuristic solvers, or state models.
        /// </summary>
        /// <returns>True if initialized successfully.</returns>
        bool Initialize();

        /// <summary>
        /// Feeds fresh telemetry and environment sensory inputs into the AI framework.
        /// </summary>
        /// <param name="telemetry">Current telemetry snapshot.</param>
        void ProcessSensoryInput(TelemetrySnapshot telemetry);

        /// <summary>
        /// Computes and generates the next flight control commands.
        /// </summary>
        /// <returns>Calculated AI command output structure.</returns>
        AICommandOutput GenerateCommands();

        /// <summary>
        /// Sets an active navigation or operational goal for the AI agent.
        /// </summary>
        /// <param name="goal">Target AI goal payload.</param>
        void SetActiveGoal(AIGoal goal);

        /// <summary>
        /// Resets internal AI memory, recurrent states, and goal queues.
        /// </summary>
        void ResetAI();
    }
}


